services:
  - type: web
    name: highrise-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ROOM_ID
        sync: false
      - key: API_KEY
        sync: false
      - key: RADIO_STREAM_URL
        value: http://127.0.0.1:8000/stream
      - key: ICECAST_SOURCE
        value: source
      - key: ICECAST_PASSWORD
        value: password
      - key: ICECAST_HOST
        value: 127.0.0.1
      - key: ICECAST_PORT
        value: "8000"
      - key: ICECAST_MOUNT
        value: /stream
