FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg ca-certificates curl unzip && curl -fsSL https://deno.land/install.sh | sh -s v2.3.0 && ln -s /root/.deno/bin/deno /usr/local/bin/deno && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir "yt-dlp[default]" yt-dlp-ejs
COPY autodj.py .
CMD ["python","-u","autodj.py"]
